### ISSUE TITLE
app header alignment on mobile

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet-tools#77] opened 2020-08-04 17:24 UTC
The alignment of the elements in the application header look great on desktop. On a phone, they seem a bit mis-aligned.

<img width="251" alt="Screen Shot 2020-08-04 at 10 20 59 AM" src="https://user-images.githubusercontent.com/11637956/89324762-a605c800-d63c-11ea-8917-614e21b15f07.png">

**Comment by ShimiSun** [comment] 2020-08-04 17:27
Thanks! Marking as a duplicate of issue  #71

**Closed** 2020-08-05 19:47 UTC
